from enum import Enum


class EventVisibility(str, Enum):
    PUBLIC = "PUBLIC"
    CREW_ONLY = "CREW_ONLY"
    FACTION_ONLY = "FACTION_ONLY"
    PRIVATE = "PRIVATE"
    SECRET = "SECRET"
    CASE_RESTRICTED = "CASE_RESTRICTED"
    AUTHORITY_ONLY = "AUTHORITY_ONLY"


class EventType(str, Enum):
    # Player Lifecycle & One-Life Permadeath
    PLAYER_CREATED = "PLAYER_CREATED"
    CHARACTER_SPAWNED = "CHARACTER_SPAWNED"
    CHARACTER_DAMAGED = "CHARACTER_DAMAGED"
    DEATH_EVENT = "DEATH_EVENT"
    KILL_EVENT = "KILL_EVENT"
    LEGACY_CREATED = "LEGACY_CREATED"

    # Crew & Politics
    PLAYER_JOINED_CREW = "PLAYER_JOINED_CREW"
    PLAYER_LEFT_CREW = "PLAYER_LEFT_CREW"
    CREW_PROMOTION = "CREW_PROMOTION"
    CREW_BETRAYAL_ATTEMPTED = "CREW_BETRAYAL_ATTEMPTED"
    MUTINY_STARTED = "MUTINY_STARTED"
    MUTINY_RESOLVED = "MUTINY_RESOLVED"

    # Business, Property & Aliases
    PROPERTY_ACQUIRED = "PROPERTY_ACQUIRED"
    BUSINESS_PURCHASED = "BUSINESS_PURCHASED"
    BUSINESS_OPERATION_RUN = "BUSINESS_OPERATION_RUN"
    ILLEGAL_OPERATION_STARTED = "ILLEGAL_OPERATION_STARTED"
    ALIAS_CREATED = "ALIAS_CREATED"
    ALIAS_LINKED = "ALIAS_LINKED"
    GOODS_SMUGGLED = "GOODS_SMUGGLED"

    # Economy & Gambling
    TRANSACTION_EXECUTED = "TRANSACTION_EXECUTED"
    GAMBLING_GAME_PLAYED = "GAMBLING_GAME_PLAYED"
    BOUNTY_ISSUED = "BOUNTY_ISSUED"
    BOUNTY_CLAIMED = "BOUNTY_CLAIMED"

    # Marine Investigations & Corruption
    CASE_OPENED = "CASE_OPENED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    EVIDENCE_DISCOVERED = "EVIDENCE_DISCOVERED"
    INTERROGATION_STARTED = "INTERROGATION_STARTED"
    INTERROGATION_MESSAGE = "INTERROGATION_MESSAGE"
    WARRANT_REQUESTED = "WARRANT_REQUESTED"
    WARRANT_DECISION = "WARRANT_DECISION"
    RAID_EXECUTED = "RAID_EXECUTED"
    BRIBE_ATTEMPTED = "BRIBE_ATTEMPTED"
    BRIBE_ACCEPTED = "BRIBE_ACCEPTED"
    BRIBE_REJECTED = "BRIBE_REJECTED"
    UNDERCOVER_OPERATION_LAUNCHED = "UNDERCOVER_OPERATION_LAUNCHED"

    # Naval & Ship System
    SHIP_PURCHASED = "SHIP_PURCHASED"
    SHIP_SAILED = "SHIP_SAILED"
    SHIP_DOCKED = "SHIP_DOCKED"
    NAVAL_COMBAT = "NAVAL_COMBAT"
    SHIP_DAMAGED = "SHIP_DAMAGED"
    SHIP_SUNK = "SHIP_SUNK"
    SHIP_REPAIRED = "SHIP_REPAIRED"
    CARGO_TRANSFERRED = "CARGO_TRANSFERRED"

    # Simulation & Scheduler
    SIMULATION_TICK = "SIMULATION_TICK"
    NPC_GOAL_PROGRESSED = "NPC_GOAL_PROGRESSED"

    # Merchant, Trade & Banking
    GOODS_TRADED = "GOODS_TRADED"
    LOAN_ISSUED = "LOAN_ISSUED"
    LOAN_REPAID = "LOAN_REPAID"
    LOAN_DEFAULTED = "LOAN_DEFAULTED"

    # Faction Protection & Protected Entities
    PROTECTION_CONTRACT_CREATED = "PROTECTION_CONTRACT_CREATED"
    PROTECTION_CONTRACT_VIOLATED = "PROTECTION_CONTRACT_VIOLATED"
    HOSTILE_ACTION_AGAINST_PROTECTED_ENTITY = "HOSTILE_ACTION_AGAINST_PROTECTED_ENTITY"

    # Intelligence & Informant Network
    INTEL_GATHERED = "INTEL_GATHERED"
    INTEL_SOLD = "INTEL_SOLD"
    DOUBLE_AGENT_EXPOSED = "DOUBLE_AGENT_EXPOSED"

    # Contract Board & Independent Mercenaries
    CONTRACT_POSTED = "CONTRACT_POSTED"
    CONTRACT_ACCEPTED = "CONTRACT_ACCEPTED"
    CONTRACT_COMPLETED = "CONTRACT_COMPLETED"
    CONTRACT_FAILED = "CONTRACT_FAILED"

    # Salvage & Exploration
    SALVAGE_DISCOVERED = "SALVAGE_DISCOVERED"
    SALVAGE_CLAIMED = "SALVAGE_CLAIMED"

    # Game Director, Guidance, Opportunities & Living World
    OPPORTUNITY_GENERATED = "OPPORTUNITY_GENERATED"
    OPPORTUNITY_ACCEPTED = "OPPORTUNITY_ACCEPTED"
    OPPORTUNITY_COMPLETED = "OPPORTUNITY_COMPLETED"
    OPPORTUNITY_EXPIRED = "OPPORTUNITY_EXPIRED"
    STORY_THREAD_CREATED = "STORY_THREAD_CREATED"
    STORY_THREAD_UPDATED = "STORY_THREAD_UPDATED"
    STORY_THREAD_RESOLVED = "STORY_THREAD_RESOLVED"
    STORY_THREAD_MERGED = "STORY_THREAD_MERGED"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    NPC_GIFT_RECEIVED = "NPC_GIFT_RECEIVED"
    FAVOR_EARNED = "FAVOR_EARNED"
    FAVOR_EXCHANGED = "FAVOR_EXCHANGED"
    DISCOVERY_MADE = "DISCOVERY_MADE"
    REWARD_GRANTED = "REWARD_GRANTED"

