from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class ActionProposal(BaseModel):
    """Structured proposal generated by AI Action Engine from untrusted player input."""
    intent: str = Field(description="Summary of player intent")
    action_type: str = Field(description="Normalized action type e.g. EXAMINE, TALK, STEAL, BETRAY, SMUGGLE, INTERROGATE")
    target: Optional[str] = Field(default=None, description="Identified target entity, NPC, or item")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parsed action parameters")
    feasible: bool = Field(description="Physical and situational plausibility assessment")
    rejection_reason: Optional[str] = Field(default=None, description="Reason if infeasible")
    proposed_outcome: str = Field(description="SUCCESS, PARTIAL_SUCCESS, FAILURE, DETECTED, CRITICAL_SUCCESS, CRITICAL_FAILURE")
    narrative: str = Field(description="Atmospheric narrative description of the proposed resolution")
    requested_state_changes: List[Dict[str, Any]] = Field(default_factory=list, description="Non-authoritative state mutations requested")
