from typing import Optional, List
from pydantic import BaseModel, Field


class ActionProposal(BaseModel):
    """Structured proposal generated by AI Action Engine from untrusted player input."""
    intent: str = Field(description="Summary of player intent")
    action_type: str = Field(description="Normalized action type e.g. LABOR_WORK, CRIME_STEAL, EXPLORE, BETRAY, SMUGGLE, TALK, EXAMINE")
    difficulty_level: str = Field(default="MODERATE", description="TRIVIAL, EASY, MODERATE, HARD, EXTREME, IMPOSSIBLE")
    success_chance_percent: int = Field(default=65, ge=1, le=99, description="Estimated chance of success from 1 to 99 percent based on character, difficulty, and location")
    target: Optional[str] = Field(default=None, description="Identified target entity, NPC, or item")
    feasible: bool = Field(description="Physical and situational plausibility assessment")
    rejection_reason: Optional[str] = Field(default=None, description="Reason if infeasible")
    proposed_outcome: str = Field(description="SUCCESS, PARTIAL_SUCCESS, FAILURE, DETECTED, CRITICAL_SUCCESS, CRITICAL_FAILURE")
    reward_gold: int = Field(default=0, ge=0, le=1000, description="Gold earned or looted: e.g. 15-50 for manual labor/odd jobs, 50-150 for skilled trade/bounties, 100-300 for daring heists, or 0 if non-paying")
    reward_items_summary: Optional[str] = Field(default=None, description="Summary of items found or gained, or None")
    health_change: int = Field(default=0, ge=-100, le=100, description="HP gained or lost, negative for damage e.g. -10")
    wanted_level_change: int = Field(default=0, ge=0, le=3, description="Increase in wanted level if caught committing crimes")
    reputation_faction: Optional[str] = Field(default=None, description="Faction affected: marine, pirate, merchant, independent, or None")
    reputation_change: int = Field(default=0, ge=-50, le=50, description="Reputation delta for the affected faction")
    narrative: str = Field(description="Vivid atmospheric narrative describing what physically occurs")

