from typing import Optional, List
from pydantic import BaseModel, Field


class AIDiscoveryProposal(BaseModel):
    """Contextual narrative discovery generated by AI according to world threads and player state."""
    discovery_type: str = Field(
        default="SUSPICIOUS_BODY",
        description="Category: SUSPICIOUS_BODY, ABANDONED_CARGO, SECRET_MEETING, SMUGGLING_CACHE, WOUNDED_SAILOR, LOST_TREASURE, ILLEGAL_GAMBLING, HIDDEN_ROOM, FORGED_DOCUMENT, STRANGE_RELIC"
    )
    title: str = Field(description="Short, evocative title for the discovery (e.g. 'A Bloodstained Cipher in the Bilge')")
    description: str = Field(description="2-3 vivid sentences describing the scene, atmosphere, and mystery in the current location")
    suggested_actions: List[str] = Field(description="3 to 4 distinct, meaningful action choices for the player (under 75 characters each)")
    connected_thread_title: Optional[str] = Field(default=None, description="Title of the active story thread this ties into, if any")
    reward_hint: Optional[str] = Field(default=None, description="Brief hint of what might be gained (gold, intel, items, danger)")


class AIDiscoveryResolution(BaseModel):
    """Consequence resolution when a player selects an action choice on a discovery."""
    outcome_narrative: str = Field(description="2-3 sentences detailing what happens as a result of the player's choice")
    gold_reward: int = Field(default=0, ge=0, le=200, description="Amount of gold gained from the action (0 if none)")
    item_name: Optional[str] = Field(default=None, description="Name of a specific item discovered/looted, or None")
    item_type: Optional[str] = Field(default=None, description="Item type: 'consumable', 'weapon', 'tool', 'valuable', 'relic', or None")
    reputation_faction: Optional[str] = Field(default=None, description="Affected faction: 'marine', 'pirate', 'merchant', 'civilian', or None")
    reputation_delta: int = Field(default=0, ge=-25, le=25, description="Reputation change for the faction")
    thread_clue: Optional[str] = Field(default=None, description="New factual lead or discovery to add to a story thread, if relevant")
    merged_thread_title: Optional[str] = Field(default=None, description="Name of second thread to merge if a connection is revealed, or None")
